<?php

namespace AppBundle\Repository;

/**
 * acheteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acheteurRepository extends \Doctrine\ORM\EntityRepository
{
}
