<?php

namespace AppBundle\Repository;

/**
 * marchandisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marchandisRepository extends \Doctrine\ORM\EntityRepository
{
}
