<?php

namespace AppBundle\Repository;

/**
 * preteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preteurRepository extends \Doctrine\ORM\EntityRepository
{
}
