<?php

namespace AppBundle\Repository;

/**
 * reparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reparateurRepository extends \Doctrine\ORM\EntityRepository
{
}
